"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Carro_1 = require("./Carro");
var garagem_1 = require("./garagem");
var garegem = new garagem_1.Garagem();
var uno = new Carro_1.Carro(12, "Carro", 4, "julia");
console.log(uno.ObterGasolina());
uno.AdicionarGasolina();
uno.GetCarro();
uno.Dirigir(18);
garegem.AdicionarCarro(uno);
var motoca = new Carro_1.Carro(3, "motoca", 2, "tatiana");
motoca.Dirigir(4);
motoca.GetCarro();
motoca.AdicionarGasolina();
console.log(motoca.ObterGasolina());
garegem.AdicionarCarro(motoca);
var cavalo = new Carro_1.Carro(8, "cavalo", 2, "fabio");
console.log(cavalo.ObterGasolina());
cavalo.AdicionarGasolina();
cavalo.Dirigir(9);
garegem.AdicionarCarro(cavalo);
var carros = new Carro_1.Carro(0, "", 0, "");
carros.SetCarro();
carros.GetCarro();
console.log(carros.ObterGasolina());
carros.AdicionarGasolina();
carros.Dirigir(18);
garegem.AdicionarCarro(carros);
garegem.ListarCarros();
garegem.RemoverCarro(uno);
garegem.ListarCarros();
